dist: xenial
language: python
os: linux
git:
  depth: 3
cache:
  pip: true
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install:
- pip install -r requirements.txt
script:
- python map_runs.py
notifications:
  email:
    on_success: never
    on_failure: always
