dist: xenial
language: python
os: linux
git:
  depth: 3
cache:
  pip: true
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- '3.7'
install:
- pip install -r requirements.txt
script:
- python ./src/map-runs.py
notifications:
  email:
    on_success: never
    on_failure: always
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    python: '3.6'
