name: Update map

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:

    # Install dependencies:
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Main script:
    - name: Build new map
      run: python ./src/map_runs.py
